[package]
name = "pwgen"
version = "0.1.0"
authors = ["Nik Clayton <nik@ngo.org.uk>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
rand = "0.7"
gflags = "0.3"
gflags-derive = { path = "../../../" }
serde = { version = "1.0", features = ["derive"] }
